events { worker_connections 1024; }

http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

    server {
        listen 80;

        location /unlimited {
            proxy_pass http://mock_app:8080/ok;
        }

        location /limited {
            limit_req zone=api_limit burst=2 nodelay;
            limit_req_status 429;
            proxy_pass http://mock_app:8080/ok;
        }

        location /waf-challenge {
            proxy_pass http://mock_app:8080/challenge;
        }

        location /trigger-429 {
            return 429 '{"error": "Too Many Requests"}';
        }

        location /redirect-external {
            return 302 https://google.com;
        }

        location /redirect-internal {
            return 302 /unlimited;
        }
    }
}